version: "3.5"

secrets:
  bacula-auth:
    file: ./bacula-auth

services:
  mariadb-test:
    image: docker.nalogka.com/mariadb-test:6
    ports: 
      - "8000:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    secrets:
      - source: bacula-auth
        target: bacula-auth
        uid: '999'
        gid: '999'
        mode: 0440
